### ISSUE TITLE
Questions about the performance of baselines in 3D-MOLM and MolCA paper

### ISSUE THREAD

**Issue by lhkhiem28** [lsh0520/3D-MoLM#11]
Hi Zhiyuan and Sihang, 

1) I went through both your 3D-MOLM and MolCA papers and I found that the reported performances of MolT5 and MoMu for Molecule Captioning on PubChem dataset in these papers are different without an explanation. (Table 2a in MolCA paper and Table 3a in 3D-MOLM paper). Could you please explain my concern and let me know which baselines are reliable?

2) Additionally, do you have a justification for why MolCA-Galac1.3B outperforms 3D-MoLM-Llama-7B on the Molecule Captioning task?

Thank you very much for your response. Looking forward to hearing from you again.
<img width="515" alt="Screenshot 2024-04-22 005542" src="https://github.com/lsh0520/3D-MoLM/assets/65554296/82cca5fc-850d-4cef-a3d8-ba75c61acb7e">
<img width="587" alt="Screenshot 2024-04-22 005518" src="https://github.com/lsh0520/3D-MoLM/assets/65554296/94fb077b-9a70-45a0-82d3-baaa8521be38">

Thanks.

**Comment by acharkq** [comment]
Hi Khiem, 

The processed dataset used in 3D-MoLM and MolCA is different. This is because the two works used different pre-processing strategy, that 3D-MoLM includes a molecules's IUPAC name in the caption and MolCA does not. Therefore, the results are different for baselines and the results are not directly comparable


There are other differences in data-processing in addition to the one that I mention above. I recommend reference to the two paper's appendix section on details of the data-processing
